### ISSUE TITLE
Use detection models from language-detection

### ISSUE THREAD

**Issue by PanderMusubi** [roskakori/loxun#4]
There are more models available at https://code.google.com/p/language-detection/ Perhaps you could also adjust your package to be a wrapper for language-detection that is written in Java or directly use their models.

**Comment by roskakori** [comment]
I'm somewhat confused with this. Loxun does not process any information about human languages. In how far would a language detection be helpful for this library?

**Comment by PanderMusubi** [comment]
Oops, I think I submitted this to the wrong project. :S

**Comment by PanderMusubi** [comment]
Now I have to dig through my browser history from two months ago too see where it was intended. ;)

**Comment by roskakori** [comment]
No problem. Good luck with your browser archeology expedition. ;)
